### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by rugk** [k9mail/k-9-design#1]
I really liked the one in https://github.com/k9mail/k-9/issues/1723 by @moctodot.

**Comment by juliakorbut** [comment]
Again, you're welcome to use or create your own icon.

**Comment by cketti** [comment]
It was my understanding that this repository will be used for collaboration on the design. https://github.com/k9mail/k-9/issues/1723 already contains quite a few suggestions for a new icon and I welcome the diverse proposals.

The ultimate decision on what makes it into the app, however, lies with the project lead. Currently, that's me. After consultation of the main contributors back in January I decided to go with the icon [merged here](https://github.com/k9mail/k-9/pull/2082/files) for the next major version. That is not to say we can't change the icon with another major app version.

Ideally, we pick an icon based on popularity. My requirement is simply that it needs to be true to the origins, i.e. K-9, the robot dog, needs to be recognizable/present in some form.

**Comment by juliakorbut** [comment]
Hey @cketti - the reason I wanted to close this issue for the time being is that I'm working on a user survey for the redesign in general, and that'll include the icon. 

I disagree with the merged icon being the best approach for now. I've have taken a lot of care to design an icon readable in small sizes and against a variety of wallpaper colors and textures. 

From my expertise, a better approach could be to [keep the old (current) icon](https://avatars1.githubusercontent.com/u/567044?v=3&s=200) until we receive feedback from the user survey. It'll create a lot of thrash otherwise.

**Comment by juliakorbut** [comment]
Hey @cketti - the reason I wanted to close this issue for the time being is that I'm working on a user survey for the redesign in general, and that'll include the icon. If everyone opened an issue based on personal opinions, we'll end up with a lot of noise. A central survey can have room for non-designers to comment, and we could look at feedback trends in a more quantified manner. The best use of issues to me is for feature requests or designers to collaborate and reference contributions.

I disagree with the merged icon being the best approach for now. I've have taken a lot of care to design an icon readable in small sizes and against a variety of wallpaper colors and textures. 

From my expertise, a better approach could be to [keep the old (current) icon](https://avatars1.githubusercontent.com/u/567044?v=3&s=200) until we receive feedback from the user survey. It'll create a lot of thrash otherwise.

**Comment by juliakorbut** [comment]
Hey @cketti - the reason I wanted to close this issue for the time being is that I'm working on a user survey for the redesign in general, and that'll include the icon. If everyone opened an issue based on personal opinions, we'll end up with a lot of noise. A central survey can have room for non-designers to comment, and we could look at feedback trends in a more quantified manner. The best use of issues to me is for feature requests or designers to collaborate and reference contributions.

I disagree with the merged icon being the best approach for now. I've have taken a lot of care to design an icon readable in small sizes and against a variety of wallpaper colors and textures. It was published after January so not sure if it was included in the discussion.

![k-9_app](https://cloud.githubusercontent.com/assets/8000951/23281428/464b73b4-f9eb-11e6-962b-99f9c2ba97a3.png)

From my expertise, a better approach could be to [keep the old (current) icon](https://avatars1.githubusercontent.com/u/567044?v=3&s=200) until we receive feedback from the user survey and have a majority vote. It'll create a lot of thrash otherwise.

**Comment by juliakorbut** [comment]
Hey @cketti - the reason I wanted to close this issue for the time being is that I'm working on a user survey for the redesign in general, and that'll include the icon. 

If everyone opened an issue based on personal opinions, we'll end up with a lot of noise. A central survey can have room for non-designers to comment, and we could look at feedback trends in a more quantified manner. The best use of issues to me is for feature requests or designers to collaborate and reference contributions.

I disagree with the merged icon being the best approach for now. I've have taken a lot of care to design an icon readable in small sizes and against a variety of wallpaper colors and textures. It was published after January so not sure if it was included in the discussion.

From my expertise, a better approach could be to [keep the old (current) icon](https://avatars1.githubusercontent.com/u/567044?v=3&s=200) until we receive feedback from the user survey and have a majority vote. It'll create a lot of thrash otherwise.

**Comment by Immontalis** [comment]
Hey @juliakorbut the new icon is awesome pls dont use the old own this is very ugly 
But I am glad you are now still working on a Material Design yuhuuuuu 💃

**Comment by n-drw** [comment]
Found this thread while taking a look at the proposed icons and as a dedicated K9 user, I'd have to say that the proposed icon that @juliakorbut has a coherent usage of a pattern of colors and flat design that works perfectly by eliminating the overuse of gaudy shadow drops that are found in icon proposal by @moctodot. 

Also, how conducive is this "issue' to the redesign really? The wordage being used in the title of this issue only exemplifies that @rugk has an _opinion_ and not so much an _issue_, thereby this thread is pointless and should have been privately discussed among the two designers proposing the icons.

**Comment by rugk** [comment]
Okay, okay, renamed. So discuss everything about the icon here…

**Comment by rugk** [comment]
Maybe we should create a comment for each icon and let users use the :+1: and :-1: buttons… :smiley: (they are already used, see initial comment in this issue)

**Comment by juliakorbut** [comment]
I agree a vote needs to happen but don't think this is the best forum for voting as it excludes non-dev and non-designer K-9 users. I'm working on a user survey for that.

**Comment by juliakorbut** [comment]
Also, just for comparison. This will be sent out in a survey I'll include here soon for broader feedback.

Notice how the current icons don't align to a grid, and aren't clear in small sizes. None of them also look like a dog, or a robot. 

I've also grayed out my icon for comparison so the way the shape itself scales down is more noticeable.

![comparison](https://cloud.githubusercontent.com/assets/8000951/24119903/249da280-0d89-11e7-9348-02db615c68a9.png)

**Comment by juliakorbut** [comment]
Also, just for comparison. This will be sent out in a survey I'll include here soon for broader feedback.

Notice how the current icons don't align to a grid, so there's a lot of weird proportions. They get lost in small sizes. The envelope is barely visible. None of them also look like a dog, or a robot. The last one looks like a cat. 

I've also grayed out my icon for comparison so the way the shape itself scales down is more noticeable.

![comparison](https://cloud.githubusercontent.com/assets/8000951/24119903/249da280-0d89-11e7-9348-02db615c68a9.png)


Current K-9: 
![current](https://avatars1.githubusercontent.com/u/567044?v=3&s=200)

**Comment by rugk** [comment]
Why did you include your icon twice (first two lines)? Or is there actually a difference between the first two lines?

In general: What about using a (maybe default Android) background picture instead of just black/white, to make it a bit less theoretical? :wink:

**Comment by ArchangeGabriel** [comment]
Aren’t the different icon sizes for different resolution? In which cases those comparisons do not really make sense, right? So I agree with @rugk that having a real world situation (with K-9 icon amongst other on a typical Android screen) would probably be more accurate.

On a more personal side, I appreciate that you put a lot of effort in making your icon look good at all sizes, but like @rugk I’m not really fond of your design in comparison to @moctodot one particularly.

**Comment by juliakorbut** [comment]
The K-9 icon was [just updated](https://avatars1.githubusercontent.com/u/567044?v=3&s=200), so you can ignore this thread for now as it's aimless. I'm closing this issue, and will link out to a survey in the README once I'm done - you can definitely vote on your designs and icon picks there.

**Comment by cketti** [comment]
I didn't mean to end the search for a new icon. I was changing some settings of the Github organization and noticed it was still using the "old" icon, so I changed it.
As I wrote before, the decision to make this the new app icon (at least for the next major version) was made some time ago and I don't intend to go back on that. I think it would be unfair to the person who polished it with the understanding it will be used in the next version.

But I also [wrote](https://github.com/k9mail/k-9/issues/1723#issuecomment-271270634) I'm not in love with any of the icons proposed so far. So I'd very much like for the icon proposals to keep coming.
I believe at this stage having wildly different proposals would help to find a direction we want to move into. After that direction is found work can start on making the icon work on different screen sizes etc.

**Comment by juliakorbut** [comment]
I agree with all of what's said above. Merely suggesting this issue is not the best way to 'vote' or decide on that. It's pointless since a proper survey is being prepared right now for more broad and quantifiable feedback.

**Comment by rugk** [comment]
Off-topic, but @cketti, you might also want to change the URL of the K9 mail organisation. It still points to Google Code…

As for the icon I am looking forward to the survey. I hope, you'll use real-world pictures, i.e. the proposed K9 mail icons near to other icons such as it has been posted [here](https://github.com/k9mail/k-9/issues/1723#issuecomment-270895726):
![icon](https://cloud.githubusercontent.com/assets/1908896/21718106/5af8d776-d415-11e6-8f5c-6ff197ae5338.png)

**Comment by rugk** [comment]
BTW the icon in the Readme here still needs updating.
